spring:
    profiles: test
name: test-YAML
environment: test
 
---
spring:
  profiles: dev
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: A@ssw0rd
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
name: dev-YAML
environment: dev
 
---
spring:
    profiles: prod
    datasource:
      driverClassName: org.postgresql.Driver
      url: ${JDBC_DATABASE_URL}
      username: ${JDBC_DATABASE_USERNAME}
      password: ${JDBC_DATABASE_PASSWORD}
    jpa:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.ddl-auto: update
      generate-ddl: true
      show-sql: true
name: prod-YAML
environment: production
